### ISSUE TITLE
include the version of godot used in the demos and games linked

### ISSUE THREAD

**Issue by curioussavage** [Calinou/awesome-godot#80] opened 2018-02-14 00:44 UTC
I suppose this could apply to other things too. Some of the games linked are older and I (and probably many other people) am looking for godot 3 examples.

**Comment by pwab** [comment] 2018-02-14 08:03
Maybe a duplicate of #66

**Comment by Calinou** [comment] 2018-02-14 21:47
Duplicate of #66, please continue the discussion there. 😃

**Closed as completed by Calinou** 2018-02-14 21:47 UTC
